### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/waveglow#106]
Running demo like:
`python3 inference.py -f mel_spectrograms/LJ001-0094.wav.pt -w waveglow_256channels.pt -o . --is_fp16 -s 0.6`

Get error:

```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 36, in main
    mel_files = files_to_list(mel_files)
  File "/Users/user/external_projects/text-to-speech/waveglow/mel2samp.py", line 47, in files_to_list
    files = f.readlines()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by mrgloom** [comment]
Running like:
`python3 inference.py -f <(ls mel_spectrograms/*.pt) -w waveglow_256channels.pt -o . --is_fp16 -s 0.6`

Get error:
```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 37, in main
    waveglow = torch.load(waveglow_path)['model']
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 385, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 572, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 535, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
```

**Comment by mrgloom** [comment]
After adding `map_location='cpu'` here
https://github.com/NVIDIA/waveglow/blob/61adc104147f569b9136c39bb8ad296f6d42bb43/inference.py#L37
and here
https://github.com/NVIDIA/waveglow/blob/61adc104147f569b9136c39bb8ad296f6d42bb43/inference.py#L50

```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 39, in main
    waveglow.cuda().eval()
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 263, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 196, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 263, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

And after removing cuda here
https://github.com/NVIDIA/waveglow/blob/61adc104147f569b9136c39bb8ad296f6d42bb43/inference.py#L39
and here
https://github.com/NVIDIA/waveglow/blob/61adc104147f569b9136c39bb8ad296f6d42bb43/inference.py#L51
and here
https://github.com/NVIDIA/waveglow/blob/61adc104147f569b9136c39bb8ad296f6d42bb43/inference.py#L46

```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 55, in main
    audio = waveglow.infer(mel, sigma=sigma)
  File "/Users/user/external_projects/text-to-speech/waveglow/glow.py", line 252, in infer
    spect = self.upsample(spect)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 616, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: _thnn_conv_transpose2d_forward is not implemented for type torch.HalfTensor
```

After running like:
`python3 inference.py -f <(ls mel_spectrograms/*.pt) -w waveglow_256channels.pt -o . -s 0.6`

```
/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 55, in main
    audio = waveglow.infer(mel, sigma=sigma)
  File "/Users/user/external_projects/text-to-speech/waveglow/glow.py", line 267, in infer
    spect.size(2)).normal_()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by mrgloom** [comment]
After removing `cuda` from `glow.py` it works, but it very slow on CPU.
https://github.com/NVIDIA/waveglow/issues/53

**Comment by mrgloom** [comment]
```
grep -rnw . -e ".*cuda().*"
./denoiser.py:15:                         win_length=win_length).cuda()
./denoiser.py:36:        audio_spec, audio_angles = self.stft.transform(audio.cuda().float())
./train.py:55:    model_for_saving = WaveGlow(**waveglow_config).cuda()
./train.py:72:    model = WaveGlow(**waveglow_config).cuda()
./train.py:114:            mel = torch.autograd.Variable(mel.cuda())
./train.py:115:            audio = torch.autograd.Variable(audio.cuda())
./tacotron2/utils.py:8:    ids = torch.arange(0, max_len).long().cuda()
./tacotron2/train.py:80:    model = Tacotron2(hparams).cuda()
./tacotron2/inference.ipynb:125:    "    torch.from_numpy(sequence)).cuda().long()"
```

Removed "cuda()" under `denoiser.py`

**Comment by TotzkePaul** [comment]
I used notepad++'s "Convert to UTF-8" of the LJ001-????.wav.pt files and then it worked.
