### ISSUE TITLE
After steps from README.md for getting audio: ModuleNotFoundError: No module named 'librosa'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [NVIDIA/waveglow#125]
```
$ python3 inference.py -f <(ls mel_spectrograms/*.pt) -w waveglow_old.pt -o . --is_fp16 -s 0.6
Traceback (most recent call last):
  File "inference.py", line 30, in <module>
    from mel2samp import files_to_list, MAX_WAV_VALUE
  File "/home/vitaly_zdanevich/waveglow/mel2samp.py", line 38, in <module>
    from tacotron2.layers import TacotronSTFT
  File "/home/vitaly_zdanevich/waveglow/tacotron2/layers.py", line 2, in <module>
    from librosa.filters import mel as librosa_mel_fn
ModuleNotFoundError: No module named 'librosa'
```

**Comment by vitaly-zdanevich** [comment]
I tried to install it with the same result:
```
$ pip3 install librosa
Requirement already satisfied: librosa in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: numpy>=1.8.0 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from librosa)
Requirement already satisfied: joblib>=0.7.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.5/site-packages (from librosa)
Requirement already satisfied: six>=1.3 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: resampy>=0.2.0 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from librosa)
Requirement already satisfied: audioread>=2.0.0 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from librosa)
Requirement already satisfied: scipy>=0.14.0 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from librosa)
Requirement already satisfied: intel-scipy in /usr/local/lib/python3.5/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: pydaal in /usr/local/lib/python3.5/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: numba>=0.32 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from resampy>=0.2.0->librosa)
Requirement already satisfied: intel-numpy in /usr/local/lib/python3.5/dist-packages (from intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: tbb4py==2019.* in /usr/local/lib/python3.5/dist-packages (from pydaal->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: daal==2019.* in /usr/local/lib/python3.5/dist-packages (from pydaal->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: llvmlite>=0.29.0 in /home/vitaly_zdanevich/.local/lib/python3.5/site-packages (from numba>=0.32->resampy>=0.2.0->librosa)
Requirement already satisfied: mkl-fft in /usr/local/lib/python3.5/dist-packages (from intel-numpy->intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: mkl-random in /usr/local/lib/python3.5/dist-packages (from intel-numpy->intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: mkl in /usr/local/lib/python3.5/dist-packages (from intel-numpy->intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: icc-rt in /usr/local/lib/python3.5/dist-packages (from intel-numpy->intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: tbb==2019.* in /usr/local/lib/python3.5/dist-packages (from tbb4py==2019.*->pydaal->scikit-learn!=0.19.0,>=0.14.0->librosa)
Requirement already satisfied: intel-openmp in /usr/local/lib/python3.5/dist-packages (from mkl->intel-numpy->intel-scipy->scikit-learn!=0.19.0,>=0.14.0->librosa)
```

**Comment by rafaelvalle** [comment]
This is probably related to your setup, not the repo.
