### ISSUE TITLE
RuntimeError: lu: MAGMA library not found in compilation. Please rebuild with MAGMA.

### ISSUE THREAD

**Issue by caixxiong** [NVIDIA/waveglow#141]
which MAGMA version should i install?

**Comment by petronny** [comment]
@caixxiong and I are classmates and I will provide more details.

The traceback is:
```
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 125, in train
    outputs = model((mel, audio))
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cai-x18/tts/wglow/glow.py", line 233, in forward
    audio, log_det_W = self.convinv[k](audio)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cai-x18/tts/wglow/glow.py", line 100, in forward
    log_det_W = batch_size * n_of_groups * torch.logdet(W)
RuntimeError: lu: MAGMA library not found in compilation. Please rebuild with MAGMA.
```
The problem is we can't do `torch.logdet(W)` on GPU without building with MAGMA.

He is using Archlinux and installed pytorch with `pacman -S python-pytorch-cuda`.
However, `python-pytorch-cuda` isn't built with MAGMA since magma isn't in the official Archlinux repository yet. I've filed a [bug report](https://bugs.archlinux.org/task/63347) about it.

For now, there is another solution is to do `torch.logdet(W)` on CPU. So change
```
log_det_W = batch_size * n_of_groups * torch.logdet(W)
```
to
```
log_det_W = batch_size * n_of_groups * torch.logdet(W.cpu()).cuda()
```
or
```
log_det_W = batch_size * n_of_groups * W.cpu().logdet().cuda()
```
will work.

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
