### ISSUE TITLE
Can a trained model continue training with different number of GPUs?

### ISSUE THREAD

**Issue by migk153** [NVIDIA/waveglow#191]
Hello, I would like to ask about an issue I am going through.

I had a trained waveglow model which was trained with 2 GPUs.
Then, I had some changes on my environment and now I have 3 GPUs.

So, I tried to continue training the model with 2 GPUs in my new environment of 3 GPUs.
When I try do this, looks like the codes are running but when I check the GPUs with nvidia-smi
none of the GPUs are being used, except for couple of seconds at the beginning.

I tried to figure out what is the problem and find out that training from scratch with 3 GPUs works just fine. So, I would like to know what is the problem here. Does the waveglow model only work on the same number of GPUs when trainning?

By the way, I tried to use 2 GPUs on my env of 3 GPUs editing some lines of codes but the result was the above mentioned circumstance having no using GPU.
Also, I would like to mention that I don't have deep understanding in Deep Learning.

Thanks in advance.

**Comment by CookiePPP** [comment]
How are you telling WaveGlow to use 2 GPU's?

---

https://github.com/NVIDIA/waveglow/blob/master/distributed.py#L151
```
    num_gpus = torch.cuda.device_count()
```
The number of GPU's expected is the number of GPU's that can be found by pytorch.
If you want to use a smaller portion of GPU's then you'll need to 'hide' the GPU's using something along the lines of `CUDA_VISIBLE_DEVICES=0,1,2`, e.g;
`CUDA_VISIBLE_DEVICES=0,1 python3 distributed.py -c config` would use the first 2 GPU's in your system.

---

For reference, pytorch will wait at this line till `world_size` number of GPU's have connected to the distributed pool then start processing.
https://github.com/NVIDIA/waveglow/blob/master/distributed.py#L51
```
    dist.init_process_group(dist_backend, init_method=dist_url,
                            world_size=num_gpus, rank=rank,
                            group_name=group_name)
```

**Comment by migk153** [comment]
@CookiePPP thanks for your reply.

I tried what you gave me, but it gives me the following error.

====================================================

  File "/home/centos/anaconda3/envs/python3_custom_base/lib/python3.6/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 91, in train
    optimizer)
  File "train.py", line 45, in load_checkpoint
    optimizer.load_state_dict(checkpoint_dict['optimizer'])
  File "/home/centos/anaconda3/envs/python3_custom_base/lib/python3.6/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

====================================================

And also it is the same thing I had when I try to continue training with 3 GPUs.

**Comment by cereballo** [comment]
Late to the party here, but I was able to overcome this by modifying one line in load_checkpoint:
`torch.cuda.set_rng_state_all(checkpoint['cuda_rng_state_all'][:num_gpus])`
I also added `num_gpus` to the args of the function.

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
