### ISSUE TITLE
Inference Error：ValueError: invalid buffering size

### ISSUE THREAD

**Issue by lqniunjunlper** [NVIDIA/waveglow#192]
Traceback (most recent call last):
  File "/workdir/waveglow/inference.py", line 75, in <module>
    args.output_dir, args.sampling_rate, args.is_fp16)
  File "/workdir/waveglow/inference.py", line 35, in main
    waveglow = torch.load(waveglow_path)['model']
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
ValueError: invalid buffering siz

**Comment by lqniunjunlper** [comment]
Waveglow model size is about 4GB. 
Using is_fp16 can reduce model size ?
