### ISSUE TITLE
device=cpu, still tries to use GPU?

### ISSUE THREAD

**Issue by michael-conrad** [NVIDIA/waveglow#224]
device="cpu", still tries to use GPU?

Using the pip installed version:

```bash
pip install waveglow-vocoder
```

The following is my test code that is failing with GPU out of memory even though I specified "cpu" (the GPU is in USE):

```python
import librosa
import torch
import soundfile as sf
import numpy as np

from waveglow_vocoder import WaveGlowVocoder

y = np.load("1.npy")
y_tensor = torch.from_numpy(y).to(device='cpu', dtype=torch.float32)

WV = WaveGlowVocoder(device="cpu")
mel = WV.wav2mel(y_tensor)
print(mel)
wav = WV.mel2wav(mel)
wav = wav[0].cpu().numpy()

sf.write("wg1.wav", wav, sr)
```

Here is the stacktrace:

```python
python data/cherokee/test1.py 
WARNING:root:Using CPU for WaveGlow Vocoder, this might be extremely slow. Please set device="cuda" if you have GPU support.
Using cache found in /home/muksihs/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub
Traceback (most recent call last):
  File "data/cherokee/test1.py", line 13, in <module>
    WV = WaveGlowVocoder(device="cpu")
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/waveglow_vocoder/vocoder.py", line 31, in __init__
    waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/hub.py", line 359, in load
    model = entry(*args, **kwargs)
  File "/home/muksihs/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/hubconf.py", line 200, in nvidia_waveglow
    ckpt = torch.load(ckpt_file)
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/serialization.py", line 576, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/serialization.py", line 155, in default_restore_location
    result = fn(storage, location)
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/serialization.py", line 135, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/muksihs/git/Multilingual_Text_to_Speech/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 634, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
```
```

**Comment by rafaelvalle** [comment]
```with torch.no_grad():```
