### ISSUE TITLE
ModuleNotFoundError: No module named 'layers'

### ISSUE THREAD

**Issue by xinxinye000** [NVIDIA/waveglow#281]
当我执行下面命令时报错：
inference.py -f mel_files.txt -w checkpoints/waveglow_6800 -o . --is_fp16 -s 0.6 

报错如下：
Traceback (most recent call last):
  File "E:\Code_test\0声码器集合\Mel_8\waveglow-master\inference.py", line 31, in <module>
    from denoiser import Denoiser
  File "E:\Code_test\0声码器集合\Mel_8\waveglow-master\denoiser.py", line 4, in <module>
    from layers import STFT
ModuleNotFoundError: No module named 'layers'

请问需要如何解决呢？
使用pip install layers 也不行，求助。

**Comment by xinxinye000** [comment]
I found some code in tacotron2
