### ISSUE TITLE
division by zero 

### ISSUE THREAD

**Issue by doctor-xiang** [NVIDIA/waveglow#60]
hello,everyone.when i ran train.py i met this erro,
WARNING: Multiple GPUs detected but no distributed group set
Only running 1 GPU. Use distributed.py for multiple GPUs
output directory checkpoints
Traceback (most recent call last):
File "train.py", line 171, in 
train(num_gpus, args.rank, args.group_name, **train_config)
File "train.py", line 106, in train
epoch_offset = max(0, int(iteration / len(train_loader)))
ZeroDivisionError: division by zero
how can i solve this problem?i have changed the size of the batchsize.is there something wrong with the NCCL?thank you

**Comment by rafaelvalle** [comment]
Are you trying to train with multiple GPUs?

**Comment by doctor-xiang** [comment]
i had solved  that ,thank you @rafaelvalle

**Comment by linlinsongyun** [comment]
how do u slove this problem?and isn there any question u met when running the distributed.py. it always gave the error
0:	0.002132172
Saving model and optimizer state at iteration 0 to checkpoints/waveglow_0
1:	-0.032706924
2:	-0.115777493
3:	-0.273104548
4:	-0.542801857
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 123, in train
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zhangying09/waveglow/distributed.py", line 125, in allreduce_params
    coalesced = _flatten_dense_tensors(grads)
  File "/home/zhangying09/waveglow/distributed.py", line 68, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: CUDA out of memory. Tried to allocate 1023.50 MiB (GPU 0; 10.92 GiB total capacity; 5.80 GiB already allocated; 887.50 MiB free; 3.35 GiB cached)

**Comment by rafaelvalle** [comment]
Closing due to inactivity.

**Comment by mataym** [comment]
> i had solved that ,thank you @rafaelvalle



> i had solved that ,thank you @rafaelvalle

hi, i met the same error in my training, how did u solve this problem? thanks!
