### ISSUE TITLE
Train is suspended when DataLoader

### ISSUE THREAD

**Issue by NewEricWang** [NVIDIA/waveglow#91]
Hi, when I run the training script, the training procedure seems to be suspended. 
I have waited for two days, but no any information is outputted on the terminal expect printing "Epoch: 0"
CPU used is 0, GPU used is also 0; GPU memory is 1713M. 

How can I resolve it? Is it the torch's reason?

**Comment by NewEricWang** [comment]
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 112, in train
    for i, batch in enumerate(train_loader):
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/restools/tools/anaconda/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
