### ISSUE TITLE
Training: RuntimeError: shape....is invalid for input of size....

### ISSUE THREAD

**Issue by Pawankhatri2k13** [NVIDIA/waveglow#94]
python train.py -c config.json

WARNING: Multiple GPUs detected but no distributed group set
Only running 1 GPU.  Use distributed.py for multiple GPUs
output directory checkpoints
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 110, in train
    for i, batch in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/workspace/waveglow/waveglow/mel2samp.py", line 102, in __getitem__
    mel = self.get_mel(audio)
  File "/workspace/waveglow/waveglow/mel2samp.py", line 82, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/workspace/waveglow/waveglow/tacotron2/layers.py", line 76, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "tacotron2/stft.py", line 84, in transform
    input_data = input_data.view(num_batches, 1, num_samples)
RuntimeError: shape '[1, 1, 16000]' is invalid for input of size 32000

**Comment by rafaelvalle** [comment]
Share your config.json.

**Comment by anderleich** [comment]
I'm getting same error here:
RuntimeError: shape '[1, 1, 39364]' is invalid for input of size 78728

Which is the solution?

**Comment by natravedrova** [comment]
You might want to convert your input audio files from stereo to mono as expected by the model.
